//
//  ChatLLMTests+MessageLifecycle
//  ChatLLMTests
//
//  Split out of ChatLLMTests.swift; part of the single @Suite(.serialized) ChatLLMTests suite.
//

import Testing
import Foundation
import MLXLMCommon
import SwiftUI
import SwiftData
import WebKit
import UIKit
import FoundationModels
@testable import ChatLLM

extension ChatLLMTests {
    @Test func resetForRegenerationClearsDeveloperMetadata() {
        let conversation = Conversation(title: "Test")
        let message = ChatLLM.Message(
            role: .assistant,
            text: "Visible",
            order: 1,
            conversation: conversation,
            isFinal: true,
            rawText: "<thinking>raw</thinking>",
            generationBackend: "MLX",
            generationModelName: "Qwen",
            generationStartedAt: Date(timeIntervalSince1970: 10),
            generationCompletedAt: Date(timeIntervalSince1970: 12)
        )

        message.resetForRegeneration()

        #expect(message.rawText == nil)
        #expect(message.generationBackend == nil)
        #expect(message.generationModelName == nil)
        #expect(message.generationStartedAt == nil)
        #expect(message.generationCompletedAt == nil)
    }

    @Test func generationCaptureIsDeveloperGatedAndBounded() {
        let message = ChatLLM.Message(
            role: .assistant,
            text: "Visible",
            order: 1
        )
        let oversizedRawText = String(
            repeating: "x",
            count: ChatLLM.Message.maximumCapturedRawTextCharacters + 1_000
        )

        message.completeGenerationCapture(
            rawText: oversizedRawText,
            captureRawText: false
        )
        #expect(message.rawText == nil)

        message.completeGenerationCapture(
            rawText: oversizedRawText,
            captureRawText: true
        )
        #expect(message.rawText?.count == ChatLLM.Message.maximumCapturedRawTextCharacters)
    }

    @Test func resetForRegenerationPreservesForcedSearchRequirement() {
        let conversation = Conversation(title: "Test")
        let message = ChatLLM.Message(
            role: .assistant,
            text: "Answer",
            order: 1,
            conversation: conversation,
            searchQuery: "latest swift release",
            requiresWebSearch: true
        )
        message.searchInvocations = [
            SearchInvocation(
                query: "old query",
                results: "Old result"
            )
        ]
        message.requiresWebSearch = true
        message.searchQuery = "latest swift release"

        message.resetForRegeneration()

        #expect(message.requiresWebSearch == true)
        #expect(message.searchQuery == "latest swift release")
        #expect(message.searchInvocations == nil)
    }
    @Test func reasoningOnlyStreamingIsNotTreatedAsEmptyOutput() async throws {
        let schema = Schema([Conversation.self, ChatLLM.Message.self, MessageAttachment.self])
        let container = try ModelContainer(
            for: schema,
            configurations: [ModelConfiguration(isStoredInMemoryOnly: true)]
        )
        let context = ModelContext(container)
        let conversation = Conversation(title: "Test")
        let viewModel = ChatViewModel(
            generator: PartialReasoningLLMGenerator(),
            context: context,
            conversation: conversation
        )

        let userMessage = ChatLLM.Message(
            role: .user,
            text: "Explain your thinking.",
            order: 0,
            conversation: conversation,
            isFinal: true
        )
        conversation.messages.append(userMessage)

        let assistantMessage = ChatLLM.Message(
            role: .assistant,
            text: "",
            order: 1,
            conversation: conversation,
            isReasoningMode: true
        )
        conversation.messages.append(assistantMessage)

        let outcome = await viewModel.streamAssistant(
            into: assistantMessage,
            basedOnHistoryUpTo: assistantMessage.order
        )

        #expect(outcome == .succeeded)
        #expect(assistantMessage.generationError == nil)
        #expect(assistantMessage.reasoning == "Analyze the request carefully.")
        #expect(assistantMessage.finalAnswer == nil)
        #expect(assistantMessage.isFinal)
    }

    @Test func longFirstMessageFallsBackToGeneratedTitle() async throws {
        let viewModel = try makeViewModel()
        let longInput = String(repeating: "swiftdata ", count: 80)
        viewModel.conversation.title = "New Chat"
        viewModel.conversation.hasAutoGeneratedTitle = false

        await viewModel.generateChatTitle(fromUserMessage: longInput)

        #expect(viewModel.conversation.title != "New Chat")
        #expect(viewModel.conversation.hasAutoGeneratedTitle)
    }

    @Test func deleteMessageAndMaybeTrimDeletesPersistentModel() async throws {
        let schema = Schema([Conversation.self, ChatLLM.Message.self, MessageAttachment.self])
        let container = try ModelContainer(
            for: schema,
            configurations: [ModelConfiguration(isStoredInMemoryOnly: true)]
        )
        let context = ModelContext(container)
        let conversation = Conversation(title: "Test")
        context.insert(conversation)

        let message = ChatLLM.Message(
            role: .user,
            text: "Delete me",
            order: 0,
            conversation: conversation,
            isFinal: true
        )
        conversation.messages.append(message)
        try context.save()

        let viewModel = ChatViewModel(
            generator: TestLLMGenerator(),
            context: context,
            conversation: conversation
        )

        await viewModel.deleteMessageAndMaybeTrim(message)

        let remainingMessages = try context.fetch(FetchDescriptor<ChatLLM.Message>())
        #expect(!conversation.messages.contains(where: { $0.id == message.id }))
        #expect(!remainingMessages.contains(where: { $0.id == message.id }))
    }

    @Test func rewindingForEditKeepsTheSelectedTurnAndDeletesEverythingAfterIt() async throws {
        let schema = Schema([Conversation.self, ChatLLM.Message.self, MessageAttachment.self])
        let container = try ModelContainer(
            for: schema,
            configurations: [ModelConfiguration(isStoredInMemoryOnly: true)]
        )
        let context = ModelContext(container)
        let conversation = Conversation(title: "Test")
        context.insert(conversation)

        let messages = [
            ChatLLM.Message(
                role: .user,
                text: "Keep this question",
                order: 0,
                conversation: conversation,
                isFinal: true
            ),
            ChatLLM.Message(
                role: .assistant,
                text: "Keep this answer",
                order: 1,
                conversation: conversation,
                isFinal: true
            ),
            ChatLLM.Message(
                role: .user,
                text: "Put this back in the composer",
                order: 2,
                conversation: conversation,
                isFinal: true
            ),
            ChatLLM.Message(
                role: .assistant,
                text: "Delete this answer",
                order: 3,
                conversation: conversation,
                isFinal: true
            )
        ]
        conversation.messages.append(contentsOf: messages)
        try context.save()

        let viewModel = ChatViewModel(
            generator: TestLLMGenerator(),
            context: context,
            conversation: conversation
        )

        let restoredText = viewModel.rewindForEditingUserMessage(
            messageID: messages[2].id,
            replacementText: "Edited question"
        )
        let persistedMessages = try context.fetch(FetchDescriptor<ChatLLM.Message>())

        #expect(restoredText?.restoredText == "Put this back in the composer")
        #expect(restoredText?.requiresTitleRegeneration == false)
        #expect(conversation.messages.sortedByOrder.map(\.text) == [
            "Keep this question",
            "Keep this answer",
            "Edited question"
        ])
        #expect(Set(persistedMessages.map(\.id)) == Set(messages.prefix(3).map(\.id)))

        conversation.title = "Generated title"
        conversation.hasAutoGeneratedTitle = true
        let firstMessageText = viewModel.rewindForEditingUserMessage(
            messageID: messages[0].id,
            replacementText: "Updated naming topic"
        )

        #expect(firstMessageText?.restoredText == "Keep this question")
        #expect(firstMessageText?.requiresTitleRegeneration == true)
        #expect(conversation.messages.map(\.id) == [messages[0].id])
        #expect(conversation.messages.first?.text == "Updated naming topic")
        #expect(conversation.title == "New Chat")
        #expect(!conversation.hasAutoGeneratedTitle)

        let editedFirstMessage = String(repeating: "Updated naming topic ", count: 30)
        await viewModel.send(
            userText: editedFirstMessage,
            disableToolCalls: true,
            regenerateTitle: firstMessageText?.requiresTitleRegeneration ?? false,
            editedUserMessageID: firstMessageText?.messageID
        )

        #expect(conversation.title != "New Chat")
        #expect(conversation.title != "Generated title")
        #expect(conversation.hasAutoGeneratedTitle)
    }

    @Test func editingAnImageMessagePreservesItsAttachment() async throws {
        let schema = Schema([Conversation.self, ChatLLM.Message.self, MessageAttachment.self])
        let container = try ModelContainer(
            for: schema,
            configurations: [ModelConfiguration(isStoredInMemoryOnly: true)]
        )
        let context = ModelContext(container)
        let conversation = Conversation(title: "Image chat")
        context.insert(conversation)

        let userMessage = ChatLLM.Message(
            role: .user,
            text: "Describe this image",
            order: 0,
            conversation: conversation,
            isFinal: true
        )
        let attachment = MessageAttachment(
            type: .image,
            fileURL: URL(fileURLWithPath: "/tmp/edited-image.jpg"),
            fileName: "edited-image.jpg"
        )
        attachment.message = userMessage
        userMessage.attachments.append(attachment)
        conversation.messages.append(userMessage)
        conversation.messages.append(
            ChatLLM.Message(
                role: .assistant,
                text: "Previous answer",
                order: 1,
                conversation: conversation,
                isFinal: true
            )
        )
        try context.save()

        let viewModel = ChatViewModel(
            generator: TestLLMGenerator(),
            context: context,
            conversation: conversation
        )
        let rewind = try #require(viewModel.rewindForEditingUserMessage(
            messageID: userMessage.id,
            replacementText: "Updated image question"
        ))

        let preparedMessage = try #require(
            viewModel.prepareUserMessageForSend(
                "Updated image question",
                replacingMessageID: rewind.messageID
            )
        )
        try context.save()

        let persistedAttachments = try context.fetch(FetchDescriptor<MessageAttachment>())
        #expect(preparedMessage.message.id == userMessage.id)
        #expect(conversation.messages.first?.id == userMessage.id)
        #expect(userMessage.attachments.map(\.id) == [attachment.id])
        #expect(persistedAttachments.map(\.id) == [attachment.id])
        #expect(attachment.message?.id == userMessage.id)
    }

    @Test func editingTheFirstMessagePreservesAManuallyOwnedTitle() throws {
        let schema = Schema([Conversation.self, ChatLLM.Message.self, MessageAttachment.self])
        let container = try ModelContainer(
            for: schema,
            configurations: [ModelConfiguration(isStoredInMemoryOnly: true)]
        )
        let context = ModelContext(container)
        let conversation = Conversation(
            title: "My custom title",
            hasAutoGeneratedTitle: false
        )
        context.insert(conversation)

        let userMessage = ChatLLM.Message(
            role: .user,
            text: "Original question",
            order: 0,
            conversation: conversation,
            isFinal: true
        )
        conversation.messages.append(userMessage)
        try context.save()

        let viewModel = ChatViewModel(
            generator: TestLLMGenerator(),
            context: context,
            conversation: conversation
        )
        let rewind = viewModel.rewindForEditingUserMessage(
            messageID: userMessage.id,
            replacementText: "Edited question"
        )

        #expect(rewind?.requiresTitleRegeneration == false)
        #expect(conversation.title == "My custom title")
        #expect(!conversation.hasAutoGeneratedTitle)
    }

    @Test func selectingModelPersistsChoiceToConversationStore() throws {
        let schema = Schema([Conversation.self, ChatLLM.Message.self, MessageAttachment.self])
        let container = try ModelContainer(
            for: schema,
            configurations: [ModelConfiguration(isStoredInMemoryOnly: true)]
        )
        let context = ModelContext(container)
        let conversation = Conversation(title: "Persisted")
        context.insert(conversation)
        try context.save()

        let bridge = ModelBackendBridge.shared
        let originalBackend = bridge.selectedBackend
        let originalModelID = bridge.selectedModelID
        let originalConversation = bridge.activeConversation
        defer {
            bridge.activeConversation = originalConversation
            bridge.selectedBackend = originalBackend
            bridge.selectedModelID = originalModelID
        }

        bridge.bindConversation(conversation)
        bridge.selectedBackend = .foundationModels
        bridge.selectModel("persisted-model", source: "test")

        let verificationContext = ModelContext(container)
        let storedConversation = try #require(
            verificationContext.fetch(FetchDescriptor<Conversation>()).first
        )

        #expect(storedConversation.preferredModelID == "persisted-model")
    }

    @Test func bridgeDisplayNameUsesSelectedModelInsteadOfStaleLoadedModel() {
        let bridge = ModelBackendBridge()
        let manager = MLXModelManager()
        let loadedModel = try! #require(manager.model(withID: "qwen3.5-4b-4bit-hybrid"))

        manager.currentModel = loadedModel
        bridge.modelManager = manager
        bridge.selectedBackend = .mlx
        bridge.selectedModelID = "qwen3.5-0.8b-4bit"

        #expect(bridge.currentModelDisplayName == "Qwen 3.5 (0.8B (4-bit))")
    }

    @Test func bridgeDisplayNameFallsBackForPersistedSmolLM3Selection() {
        let bridge = ModelBackendBridge()
        bridge.modelManager = nil
        bridge.selectedBackend = .mlx
        bridge.selectedModelID = "smollm3-3b-4bit"

        #expect(bridge.currentModelDisplayName == "SmolLM3 (3B (4-bit))")
    }

    @Test func reasoningAvailabilityTracksSelectedModelSupport() {
        let bridge = ModelBackendBridge()
        let manager = MLXModelManager()
        let plainModel = MLXModelManager.MLXModelInfo(
            id: "plain-local-model",
            name: "Plain Local",
            localDirName: "PlainLocal",
            hfRepoId: "local/plain",
            parameters: "1B",
            downloadSizeLabel: "1 GB",
            description: "A non-reasoning local model.",
            contextLength: 4096,
            isAvailable: true,
            supportsReasoning: false
        )
        manager.availableModels = [plainModel]
        manager.currentModel = plainModel
        bridge.modelManager = manager
        bridge.selectedBackend = .mlx
        bridge.selectedModelID = plainModel.id

        #expect(!bridge.reasoningAvailable)
    }

    @Test func reasoningAvailabilityFallsBackForPersistedSmolLM3Selection() {
        let bridge = ModelBackendBridge()
        bridge.modelManager = nil
        bridge.selectedBackend = .mlx
        bridge.selectedModelID = "smollm3-3b-4bit"

        #expect(bridge.reasoningAvailable)
    }

    @Test func messageDisplayTextStripsThinkTags() {
        let message = ChatLLM.Message(
            role: .assistant,
            text: """
            <think>
            Analyze the request carefully.
            </think>

            Final answer: The tags should not be visible.
            """,
            order: 0
        )

        #expect(message.displayText == "The tags should not be visible.")
    }

    @Test func messageContentLengthCacheTracksDisplayTextAfterDirectTextMutation() {
        let message = ChatLLM.Message(
            role: .assistant,
            text: "One",
            order: 0
        )

        let initialLength = message.contentLength
        message.text = "A much longer visible answer"
        _ = message.displayText

        #expect(initialLength == 3)
        #expect(message.contentLength == message.displayText.count)
        #expect(message.contentLength == 28)
    }

    @Test func messageAttachmentStoresContainerAgnosticRelativeURL() {
        let attachment = MessageAttachment(
            type: .image,
            fileURL: URL(fileURLWithPath: "/tmp/Attachments/example.jpg"),
            fileName: "example.jpg"
        )

        #expect(attachment.fileURL.path == "example.jpg")
        #expect(!attachment.fileURL.path.hasPrefix("/"))
    }

    @Test func cancelledGenerationBeforeFirstTokenRemovesEmptyAssistantPlaceholder() async throws {
        let schema = Schema([Conversation.self, ChatLLM.Message.self, MessageAttachment.self])
        let container = try ModelContainer(
            for: schema,
            configurations: [ModelConfiguration(isStoredInMemoryOnly: true)]
        )
        let context = ModelContext(container)
        let conversation = Conversation(title: "Test")
        let viewModel = ChatViewModel(
            generator: BlockingLLMGenerator(),
            context: context,
            conversation: conversation
        )

        let sendTask = Task { await viewModel.send(userText: "Hello") }

        for _ in 0..<50 {
            if viewModel.isGenerating { break }
            try? await Task.sleep(for: .milliseconds(20))
        }

        #expect(viewModel.isGenerating)
        #expect(conversation.messages.contains(where: { $0.role == .assistant }))

        viewModel.cancelGeneration()
        await sendTask.value

        #expect(!viewModel.isGenerating)
        #expect(conversation.messages.count == 1)
        #expect(conversation.messages.allSatisfy { $0.role == .user })
    }

    @Test func cancelGenerationAndWaitFinishesStreamBeforeReturning() async throws {
        let schema = Schema([Conversation.self, ChatLLM.Message.self, MessageAttachment.self])
        let container = try ModelContainer(
            for: schema,
            configurations: [ModelConfiguration(isStoredInMemoryOnly: true)]
        )
        let context = ModelContext(container)
        let conversation = Conversation(title: "Test")
        let viewModel = ChatViewModel(
            generator: BlockingLLMGenerator(),
            context: context,
            conversation: conversation
        )
        let sendTask = Task { await viewModel.send(userText: "Hello") }

        for _ in 0..<50 {
            if viewModel.isGenerating { break }
            try? await Task.sleep(for: .milliseconds(20))
        }

        #expect(viewModel.isGenerating)
        #expect(await viewModel.cancelGenerationAndWait())
        await sendTask.value
        #expect(!viewModel.isGenerating)
    }
    @Test func displayTextStripsThinkingTagsAndFinalAnswerPrefix() {
        let message = Message(
            role: .assistant,
            text: "<think>weighing the options</think>Final answer: Paris is the capital.",
            order: 0
        )

        #expect(message.displayText == "Paris is the capital.")
    }

    @Test func displayTextStripsThinkingTagsRegardlessOfSpellingOrCase() {
        for opening in ["<think>", "<thinking>", "<THINK>", "<Thinking>"] {
            let closing = opening
                .replacingOccurrences(of: "<", with: "</")
            let message = Message(role: .assistant, text: "\(opening)hidden\(closing)Visible.", order: 0)
            #expect(message.displayText == "Visible.")
        }
    }

    @Test func displayTextUnwrapsAnswerTags() {
        let message = Message(role: .assistant, text: "<answer>The result is 42.</answer>", order: 0)
        #expect(message.displayText == "The result is 42.")
    }

    @Test func displayTextHidesImageContextAndAnalysisBlocks() {
        let hidden = Message(
            role: .user,
            text: "What is this?[HIDDEN_IMAGE_CONTEXT]a cat on a mat[/HIDDEN_IMAGE_CONTEXT]",
            order: 0
        )
        #expect(hidden.displayText == "What is this?")

        let analysed = Message(
            role: .user,
            text: """
            --- Image Analysis Data ---
            objects: cat, mat
            --- End Image Analysis ---
            User's question: Describe the photo.
            """,
            order: 0
        )
        #expect(analysed.displayText == "Describe the photo.")
    }

    @Test func displayTextDropsTheTrailingImageAnalysisInstruction() {
        let message = Message(
            role: .user,
            text: """
            --- Image Analysis Data ---
            objects: cat
            --- User Question ---
            Describe the photo.

            Please respond based on the image analysis data above.
            """,
            order: 0
        )

        #expect(message.displayText == "Describe the photo.")
    }

    @Test func displayTextPrefersFinalAnswerOnlyForReasoningAssistants() {
        let reasoning = Message(
            role: .assistant,
            text: "raw stream",
            order: 0,
            reasoning: "thinking",
            finalAnswer: "polished answer",
            isReasoningMode: true
        )
        #expect(reasoning.displayText == "polished answer")

        // A user message in a reasoning chat still shows its own text.
        let user = Message(
            role: .user,
            text: "raw stream",
            order: 1,
            finalAnswer: "polished answer",
            isReasoningMode: true
        )
        #expect(user.displayText == "raw stream")

        // So does an assistant outside reasoning mode.
        let plain = Message(
            role: .assistant,
            text: "raw stream",
            order: 2,
            finalAnswer: "polished answer",
            isReasoningMode: false
        )
        #expect(plain.displayText == "raw stream")
    }

    @Test func displayTextCacheInvalidatesWhenAnyContentFieldChanges() {
        // displayText memoises on a hash of text + reasoning + finalAnswer.
        // Every one of those fields has to participate, or an edit renders stale.
        let message = Message(
            role: .assistant,
            text: "first",
            order: 0,
            reasoning: "a",
            finalAnswer: "first answer",
            isReasoningMode: true
        )
        #expect(message.displayText == "first answer")

        message.finalAnswer = "second answer"
        #expect(message.displayText == "second answer")

        message.isReasoningMode = false
        message.text = "third"
        #expect(message.displayText == "third")

        message.reasoning = "b"
        #expect(message.displayText == "third")
    }

    @Test func contentLengthMeasuresWhatTheReaderSeesNotRawStorage() {
        let message = Message(
            role: .assistant,
            text: "<think>a very long hidden deliberation</think>Hi.",
            order: 0
        )

        #expect(message.displayText == "Hi.")
        #expect(message.contentLength == 3)
        #expect(message.contentLength < message.text.count)
    }

    @Test func hasContentReflectsAnyPopulatedField() {
        #expect(!Message(role: .assistant, text: "", order: 0).hasContent)
        #expect(Message(role: .assistant, text: "x", order: 0).hasContent)
        #expect(Message(role: .assistant, text: "", order: 0, reasoning: "x").hasContent)
        #expect(Message(role: .assistant, text: "", order: 0, finalAnswer: "x").hasContent)
    }

    @Test func userVisibleTextRemovesSourcesBlocks() {
        let message = Message(
            role: .assistant,
            text: "The answer.\n\n<sources>1. https://example.com</sources>",
            order: 0
        )

        #expect(message.userVisibleText == "The answer.")
        #expect(message.displayText.contains("<sources>"))
    }

    // MARK: - Sources extraction

    @Test func extractSourcesBlocksSeparatesVisibleTextFromSources() {
        let (visible, sources) = "Answer.\n\n<sources>1. https://a.example</sources>".extractSourcesBlocks()

        #expect(visible == "Answer.")
        #expect(sources == "1. https://a.example")
    }

    @Test func extractSourcesBlocksJoinsMultipleAndIgnoresEmptyOnes() {
        let (visible, sources) = "A<sources>one</sources>B<sources>  </sources>C<sources>two</sources>"
            .extractSourcesBlocks()

        #expect(visible == "ABC")
        #expect(sources == "one\n\ntwo")
    }

    @Test func extractSourcesBlocksHandlesAbsentAndSourcesOnlyText() {
        let plain = "Just an answer.".extractSourcesBlocks()
        #expect(plain.visible == "Just an answer.")
        #expect(plain.sources == nil)

        let onlySources = "<sources>1. https://a.example</sources>".extractSourcesBlocks()
        #expect(onlySources.visible.isEmpty)
        #expect(onlySources.sources == "1. https://a.example")
    }

    // MARK: - Message ordering
    @Test func rewindRefusesWhileAGenerationIsInFlight() throws {
        let viewModel = try makeChat([(.user, "First"), (.assistant, "Answer")])
        let firstID = viewModel.conversation.messages.sortedByOrder[0].id
        let before = viewModel.conversation.messages.sortedByOrder.map(\.text)

        viewModel.isGenerating = true
        #expect(viewModel.rewindForEditingUserMessage(messageID: firstID) == nil)
        viewModel.isGenerating = false

        viewModel.isRegenerating = true
        #expect(viewModel.rewindForEditingUserMessage(messageID: firstID) == nil)
        viewModel.isRegenerating = false

        // A refused rewind must not have deleted anything on its way out.
        #expect(viewModel.conversation.messages.sortedByOrder.map(\.text) == before)
    }

    @Test func rewindRefusesForAssistantTurnsAndUnknownIdentifiers() throws {
        let viewModel = try makeChat([(.user, "First"), (.assistant, "Answer")])
        let messages = viewModel.conversation.messages.sortedByOrder

        #expect(viewModel.rewindForEditingUserMessage(messageID: messages[1].id) == nil)
        #expect(viewModel.rewindForEditingUserMessage(messageID: UUID()) == nil)
        #expect(viewModel.conversation.messages.count == 2)
    }

    @Test func rewindWithoutReplacementTextKeepsTheOriginalWording() throws {
        let viewModel = try makeChat([(.user, "Original"), (.assistant, "Answer")])
        let first = viewModel.conversation.messages.sortedByOrder[0]

        let result = try #require(viewModel.rewindForEditingUserMessage(messageID: first.id))

        #expect(result.restoredText == "Original")
        #expect(result.messageID == first.id)
        #expect(viewModel.conversation.messages.map(\.text) == ["Original"])
    }

    @Test func renumberingClosesGapsLeftBehindByRemovedTurns() throws {
        let viewModel = try makeChat([(.user, "a"), (.assistant, "b"), (.user, "c")])
        let messages = viewModel.conversation.messages.sortedByOrder
        viewModel.conversation.messages.removeAll { $0.id == messages[1].id }

        viewModel.renumberMessagesByOrder()

        #expect(viewModel.conversation.messages.sortedByOrder.map(\.order) == [0, 1])
        #expect(viewModel.conversation.messages.sortedByOrder.map(\.text) == ["a", "c"])
    }

    @Test func deletingATurnRenumbersWhatRemains() async throws {
        let viewModel = try makeChat([(.user, "a"), (.assistant, "b"), (.user, "c")])
        let target = viewModel.conversation.messages.sortedByOrder[0]

        await viewModel.deleteMessageAndMaybeTrim(target)

        #expect(viewModel.conversation.messages.sortedByOrder.map(\.text) == ["b", "c"])
        #expect(viewModel.conversation.messages.sortedByOrder.map(\.order) == [0, 1])
    }
}
