//
//  ChatViewModel+Title.swift
//  On-Device_LLM_Chat
//
//  Created by Nevio on 10/24/25.
//

import Foundation
import FoundationModels
import os

extension ChatViewModel {

    // MARK: - Auto Title Generation

    internal func generateChatTitle(fromUserMessage userMessage: String) async {
        guard conversation.title == String(localized: "New Chat"),
              !conversation.hasAutoGeneratedTitle else { return }

        let cleanInput = userMessage.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !cleanInput.isEmpty else { return }

        // On MLX backend, skip Foundation Models — loading Apple Intelligence alongside
        // the MLX model competes for the same unified memory and causes OOM.
        // Derive a title from the first words of the message instead.
        if ModelBackendBridge.shared.selectedBackend == .mlx {
            let title = makeTitleFromText(cleanInput)
            conversation.title = title
            conversation.hasAutoGeneratedTitle = true
            conversation.lastUpdated = Date()
            immediateSave()
            return
        }

        guard cleanInput.count <= 500 else {
            conversation.title = makeTitleFromText(cleanInput)
            conversation.hasAutoGeneratedTitle = true
            conversation.lastUpdated = Date()
            immediateSave()
            return
        }

        let model = SystemLanguageModel.default
        guard case .available = model.availability else {
            conversation.title = makeTitleFromText(cleanInput)
            conversation.hasAutoGeneratedTitle = true
            conversation.lastUpdated = Date()
            immediateSave()
            return
        }

        let maxAttempts = 3
        var lastError: Error?

        for attempt in 1...maxAttempts {
            if attempt > 1 {
                try? await Task.sleep(for: .milliseconds(100 * (1 << (attempt - 2))))
            }
            do {
                let response = try await withFoundationModelsLock(timeout: .seconds(8)) {
                    let instructions = """
                    You create chat titles.

                    Task:
                    Generate one short title for this conversation based only on the user's first message.

                    Rules:
                    - 2 to 5 words.
                    - Plain text only.
                    - No quotes.
                    - No trailing punctuation.
                    - No labels like "Title:".
                    - No filler words such as "Help", "Question", "Chat", or "Request" unless essential.
                    - Prefer the concrete subject, task, or problem.
                    - If the message is a question, name the topic, not the question form.
                    - Preserve important technical terms exactly.
                    - Use the same language as the user's message.

                    Good examples:
                    - SwiftData Migration Error
                    - Vienna Weekend Itinerary
                    - Fix JSON Parsing Bug
                    - Compare M3 and M4

                    Bad examples:
                    - Help With SwiftData
                    - Question About Travel
                    - Can You Help Me
                    - Title: JSON Bug

                    Return only the title text.
                    """
                    let session = LanguageModelSession(instructions: instructions)
                    return try await session.respond(to: "Title for: \"\(cleanInput)\"")
                }

                let generatedTitle = response.content.trimmingCharacters(in: .whitespacesAndNewlines)
                guard !generatedTitle.isEmpty, generatedTitle.count >= 3, generatedTitle.count <= 50,
                      !generatedTitle.lowercased().contains("untitled"),
                      !generatedTitle.lowercased().contains("new chat"),
                      !generatedTitle.lowercased().hasPrefix("title:"),
                      !generatedTitle.contains("\""),
                      ![".", "!", "?"].contains(where: { generatedTitle.hasSuffix(String($0)) }) else {
                    lastError = NSError(domain: "ChatViewModel", code: -2, userInfo: [:])
                    continue
                }

                conversation.title = generatedTitle
                conversation.hasAutoGeneratedTitle = true
                conversation.lastUpdated = Date()
                immediateSave()
                return
            } catch {
                lastError = error
            }
        }

        conversation.title = makeTitleFromText(cleanInput)
        conversation.hasAutoGeneratedTitle = true
        conversation.lastUpdated = Date()
        immediateSave()
        logger.warning("Title generation failed: \(lastError?.localizedDescription ?? "unknown")")
    }

    private func makeTitleFromText(_ text: String) -> String {
        let words = text.components(separatedBy: .whitespacesAndNewlines).filter { !$0.isEmpty }
        let title = words.prefix(6).joined(separator: " ")
        if title.count > 50 { return String(title.prefix(47)) + "..." }
        return title.isEmpty ? String(localized: "Untitled Chat") : title
    }
}
