//
//  ChatViewModel+Title.swift
//  On-Device_LLM_Chat
//
//  Created by Nevio on 10/24/25.
//

import Foundation
import FoundationModels
import os

extension ChatViewModel {

    // MARK: - Auto Title Generation

    internal func generateChatTitle(fromUserMessage userMessage: String) async {
        guard conversation.title == String(localized: "New Chat"),
              !conversation.hasAutoGeneratedTitle else { return }
        conversation.hasAutoGeneratedTitle = true

        let cleanInput = userMessage.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !cleanInput.isEmpty else { return }

        // On MLX backend, skip Foundation Models — loading Apple Intelligence alongside
        // the MLX model competes for the same unified memory and causes OOM.
        // Derive a title from the first words of the message instead.
        if ModelBackendBridge.shared.selectedBackend == .mlx {
            let title = makeTitleFromText(cleanInput)
            conversation.title = title
            conversation.lastUpdated = Date()
            immediateSave()
            return
        }

        guard cleanInput.count <= 500 else { return }

        let model = SystemLanguageModel.default
        guard case .available = model.availability else {
            conversation.title = makeTitleFromText(cleanInput)
            conversation.lastUpdated = Date()
            immediateSave()
            return
        }

        let maxAttempts = 3
        var lastError: Error?

        for attempt in 1...maxAttempts {
            if attempt > 1 {
                try? await Task.sleep(for: .milliseconds(100 * (1 << (attempt - 2))))
            }
            do {
                let response = try await withFoundationModelsLock(timeout: .seconds(8)) {
                    let instructions = """
                    You are a helpful assistant that creates short, descriptive titles for chat conversations.
                    Generate a concise title (maximum 5 words) that captures the main topic or question from the user's message.
                    The title should be in title case, without quotes or trailing punctuation.
                    Return only the title text, nothing else.
                    """
                    let session = LanguageModelSession(instructions: instructions)
                    return try await session.respond(to: "Title for: \"\(cleanInput)\"")
                }

                let generatedTitle = response.content.trimmingCharacters(in: .whitespacesAndNewlines)
                guard !generatedTitle.isEmpty, generatedTitle.count >= 3, generatedTitle.count <= 50,
                      !generatedTitle.lowercased().contains("untitled"),
                      !generatedTitle.lowercased().contains("new chat"),
                      !generatedTitle.lowercased().hasPrefix("title:"),
                      !generatedTitle.contains("\""),
                      ![".", "!", "?"].contains(where: { generatedTitle.hasSuffix(String($0)) }) else {
                    lastError = NSError(domain: "ChatViewModel", code: -2, userInfo: [:])
                    continue
                }

                conversation.title = generatedTitle
                conversation.lastUpdated = Date()
                immediateSave()
                return
            } catch {
                lastError = error
            }
        }

        conversation.title = makeTitleFromText(cleanInput)
        conversation.lastUpdated = Date()
        immediateSave()
        logger.warning("Title generation failed: \(lastError?.localizedDescription ?? "unknown")")
    }

    private func makeTitleFromText(_ text: String) -> String {
        let words = text.components(separatedBy: .whitespacesAndNewlines).filter { !$0.isEmpty }
        let title = words.prefix(6).joined(separator: " ")
        if title.count > 50 { return String(title.prefix(47)) + "..." }
        return title.isEmpty ? String(localized: "Untitled Chat") : title
    }
}
