//
//  ChatViewModel+Title.swift
//  On-Device_LLM_Chat
//
//  Created by Nevio on 10/24/25.
//

import Foundation
import FoundationModels
import os

extension ChatViewModel {

    // MARK: - Auto Title Generation

    internal func generateChatTitle(fromUserMessage userMessage: String) async {
        guard conversation.title == String(localized: "New Chat"),
              !conversation.hasAutoGeneratedTitle else { return }

        // Mark attempted early so a concurrent call won't also enter this path
        conversation.hasAutoGeneratedTitle = true

        let model = SystemLanguageModel.default
        guard case .available = model.availability else {
            logger.warning("System language model not available for title generation")
            await MainActor.run {
                conversation.title = String(localized: "Untitled Chat")
                conversation.lastUpdated = Date()
                immediateSave()
            }
            return
        }

        let cleanInput = userMessage.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !cleanInput.isEmpty, cleanInput.count <= 500 else {
            return
        }

        let maxAttempts = 3
        var lastError: Error?

        for attempt in 1...maxAttempts {
            logger.info("📝 Chat naming attempt \(attempt)/\(maxAttempts)")

            if attempt > 1 {
                let delayMs = 100 * (1 << (attempt - 2)) // Exponential backoff: 100ms, 200ms, 400ms...
                try? await Task.sleep(for: .milliseconds(delayMs))
            }

            do {
                // CRITICAL FIX: Use the lock to prevent concurrent Foundation Models sessions.
                let response = try await withFoundationModelsLock(timeout: .seconds(8)) {
                    let instructions = """
                    You are a helpful assistant that creates short, descriptive titles for chat conversations.

                    Generate a concise title (maximum 5 words) that captures the main topic or question from the user's message. You are not replying to the chat, you are naming it.
                    The title should be:
                    - Clear and specific
                    - In title case (e.g., "Swift Programming Help", "Recipe for Cookies")
                    - Without quotes or punctuation at the end
                    - Professional and appropriate
                    - Do not refuse chats unless truly inappropriate - in which case, generate "Needs Review"

                    Return only the title text, nothing else.
                    """

                    let session = LanguageModelSession(instructions: instructions)
                    let prompt = "Create a short title for this conversation based on the user's message: \"\(cleanInput)\""
                    return try await session.respond(to: prompt)
                }

                let generatedTitle = response.content.trimmingCharacters(in: .whitespacesAndNewlines)

                guard !generatedTitle.isEmpty,
                      generatedTitle.count >= 3,
                      generatedTitle.count <= 50,
                      !generatedTitle.lowercased().contains("untitled"),
                      !generatedTitle.lowercased().contains("new chat"),
                      !generatedTitle.lowercased().hasPrefix("title:"),
                      !generatedTitle.contains("\""),
                      !generatedTitle.hasSuffix("."),
                      !generatedTitle.hasSuffix("!"),
                      !generatedTitle.hasSuffix("?") else {
                    logger.warning("Generated title didn't pass validation (attempt \(attempt)): '\(generatedTitle)'")
                    lastError = NSError(domain: "ChatViewModel", code: -2, userInfo: [NSLocalizedDescriptionKey: "Invalid title format"])
                    continue
                }

                let lowercased = generatedTitle.lowercased()
                let inappropriateTerms = ["error", "failed", "cannot", "unable"]
                if inappropriateTerms.contains(where: lowercased.hasPrefix) {
                    logger.warning("Generated title contains inappropriate prefix (attempt \(attempt)): '\(generatedTitle)'")
                    lastError = NSError(domain: "ChatViewModel", code: -3, userInfo: [NSLocalizedDescriptionKey: "Inappropriate title content"])
                    continue
                }

                await MainActor.run {
                    conversation.title = generatedTitle
                    conversation.lastUpdated = Date()
                    immediateSave()
                    logger.info("✅ Generated title (attempt \(attempt)): '\(generatedTitle)'")
                }
                return

            } catch {
                logger.error("Error generating chat title (attempt \(attempt)/\(maxAttempts)): \(error.localizedDescription)")
                lastError = error
            }
        }

        await MainActor.run {
            conversation.title = String(localized: "Untitled Chat")
            conversation.lastUpdated = Date()
            immediateSave()
            logger.warning("Failed to generate title after \(maxAttempts) attempts. Last error: \(lastError?.localizedDescription ?? "unknown")")
        }
    }
}
