//
//  Conversation.swift
//  On-Device_LLM_Chat
//
//  Created by Nevio on 10/24/25.
//

import Foundation
import SwiftData

@Model
final class Conversation {
    @Attribute(.unique) var id: UUID
    var title: String
    var createdAt: Date
    var lastUpdated: Date
    var reasoningMode: Bool = false
    var smartReasoningMode: Bool = false
    var hasAutoGeneratedTitle: Bool = false
    @Relationship(deleteRule: .cascade, inverse: \Message.conversation)
    var messages: [Message]

    init(
        id: UUID = UUID(),
        title: String = "New Chat",
        createdAt: Date = Date(),
        lastUpdated: Date = Date(),
        reasoningMode: Bool = false,
        smartReasoningMode: Bool = false,
        hasAutoGeneratedTitle: Bool = false,
        messages: [Message] = []
    ) {
        self.id = id
        self.title = title
        self.createdAt = createdAt
        self.lastUpdated = lastUpdated
        self.reasoningMode = reasoningMode
        self.smartReasoningMode = smartReasoningMode
        self.hasAutoGeneratedTitle = hasAutoGeneratedTitle
        self.messages = messages
    }
}
