//
//  Conversation.swift
//  On-Device_LLM_Chat
//
//  Created by Nevio on 10/24/25.
//

import Foundation
import SwiftData

@Model
final class Conversation {
    @Attribute(.unique) var id: UUID
    var title: String
    var createdAt: Date
    var lastUpdated: Date
    var reasoningMode: Bool = false
    var smartReasoningMode: Bool = false
    var hasAutoGeneratedTitle: Bool = false
    var preferredBackendRawValue: String?
    var preferredModelID: String?
    var chatPreferences: String = ""
    @Relationship(deleteRule: .cascade, inverse: \Message.conversation)
    var messages: [Message]

    init(
        id: UUID = UUID(),
        title: String = "New Chat",
        createdAt: Date = Date(),
        lastUpdated: Date = Date(),
        reasoningMode: Bool = false,
        smartReasoningMode: Bool = false,
        hasAutoGeneratedTitle: Bool = false,
        preferredBackendRawValue: String? = nil,
        preferredModelID: String? = nil,
        chatPreferences: String = "",
        messages: [Message] = []
    ) {
        self.id = id
        self.title = title
        self.createdAt = createdAt
        self.lastUpdated = lastUpdated
        self.reasoningMode = reasoningMode
        self.smartReasoningMode = smartReasoningMode
        self.hasAutoGeneratedTitle = hasAutoGeneratedTitle
        self.preferredBackendRawValue = preferredBackendRawValue
        self.preferredModelID = preferredModelID
        self.chatPreferences = chatPreferences
        self.messages = messages
    }

    var searchableVisibleText: String {
        messages
            .filter { $0.role != .system }
            .sortedByOrder
            .map(\.userVisibleText)
            .filter { !$0.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty }
            .joined(separator: "\n")
    }
}
